export enum PathConstants {
  //Public Routes
  SingIn = "/",
  SingUp = "/signup",
  ForgotPassword = "/password/forgot",
  ResetPassword = "/password/reset",
  VerifyOtp = "/account/verify",
  ERROR404 = "*",
  // AccountDeleted="/account-delete",
  //Common Routes
  TermsOfService = "/terms-of-service",
  OurAdsPolicy = "/ads-policy",
  PrivacyPolicy = "/privacy-policy",
  OurConcept = "/our-concept",
  AccountDeletes = "/account-deletes",

  //Private Routes
  Home = "/",
  Live = "/live",
  LiveNow = "/live/:id/:channel_id",
  AddPost = "/post/new",
  Updates = "/updates",
  Networks = "/network",
  NetworkView = "/network/:id",
  NetworkInviteView = "/network/invite/:type",
  networkPostView = "/network-post/:id",
  UpdatesView = "/updates/:id",
  Profile = "/me",
  IDverification = "/Idverification",
  CompleteProfile = "/profile/complete",
  FindPeople = "/profile/people",
  SelectUpdates = "/profile/category",
  YouAreIn = "/profile/completed",
  Post = "/post/:id",
  LiveJoin = "/live/join/:id/:channelId",
  EditProfile = "/me/edit",
  ChangePassword = "/me/password/change",
  Settings = "/settings",
  HashTag = "/hashtag/:hashtag",
  // UserView = "/user/:username",
  UserView = "/:username",
  DeleteAccountMe = "/account-delete",
  Messages = "/chat",
  MessageView ="/chat/:id"
}
